<a href="https://colab.research.google.com/github/RookieKiddo/deep-learning/blob/main/LossCostFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mae(y_true, y_predicted):
  total = 0
  for yt, yp in zip(y_true, y_predicted):
    #print(yt,yp)
    total += abs(yt - yp)

  print("Total Error", total)
  mae = total / len(y_true)
  return mae

In [ ]:
mae(y_true, y_predicted)

Total Error 2.5


0.5

In [ ]:
#using numpy function
np.sum(np.abs(y_predicted - y_true))

2.5

In [ ]:
#exercise: Mean Squared Error

In [ ]:
#Log Function
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([-inf])

In [ ]:
np.log([0.00000001])

array([-18.42068074])

In [ ]:
#log function implementation
# we will make eplison because we have 1 in the formula, and we might have 0
# in the log. Hence, we will get error
epsilon = 1e-15

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
1-epsilon

0.999999999999999

In [ ]:
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
np.log(y_predicted)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   0., -inf, -inf,   0.])

In [ ]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
y_predicted_new = np.array(y_predicted_new)

In [ ]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844